# Naive Bayes Algorithm

Naive Bayes Algorithm is a classification algorithm based on Bayes Theorem. It is called naive because it assumes that the features in a dataset are independent of each other. This assumption is not true in real life but it simplifies the computation and gives good results in most of the cases.

## Bayes Theorem
Bayes Theorem is a mathematical formula used for calculating conditional probability. It is defined as:

 $$P(A|B) = \\frac{P(B|A)P(A)}{P(B)}$$

where A and B are events and P(B) != 0

## Naive Bayes Algorithm

Naive Bayes Algorithm is based on Bayes Theorem. It is defined as:


 $$P(y|x_1,x_2,...,x_n) = \\frac{P(x_1,x_2,...,x_n|y)P(y)}{P(x_1,x_2,...,x_n)}$$

where y is the class variable and x1, x2, ..., xn are the features.

The algorithm assumes that the features are independent of each other. So, the above equation can be written as:

 $$P(y|x_1,x_2,...,x_n) = \\frac{P(x_1|y)P(x_2|y)...P(x_n|y)P(y)}{P(x_1,x_2,...,x_n)}$$

The denominator is constant for a given input. So, the equation can be written as:

$$P(y|x_1,x_2,...,x_n) \\propto P(x_1|y)P(x_2|y)...P(x_n|y)P(y)$$

The class with the highest probability is the output of the algorithm.

## Types of Naive Bayes Algorithm

There are three types of Naive Bayes Algorithm:

1. Gaussian Naive Bayes: It is used in classification and assumes that the features follow a normal distribution.
2. Multinomial Naive Bayes: It is used for discrete data and assumes that the features follow a multinomial distribution.
3. Bernoulli Naive Bayes: It is used for binary/categorical data and assumes that the features follow a Bernoulli distribution.


In [4]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB , BernoulliNB , MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.datasets import load_iris


In [2]:
iris = load_iris()

X = iris.data
y = iris.target

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [10]:
gnb = GaussianNB()

gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Classification Report: \n", classification_report(y_test,y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test,y_pred))

Accuracy:  1.0
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
# using multinomial naive bayes

mnb = MultinomialNB()

mnb.fit(X_train,y_train)

y_pred = mnb.predict(X_test)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Classification Report: \n", classification_report(y_test,y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test,y_pred))

Accuracy:  0.9
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30

Confusion Matrix: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [11]:
bnb = BernoulliNB()

bnb.fit(X_train,y_train)

y_pred = bnb.predict(X_test)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Classification Report: \n", classification_report(y_test,y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test,y_pred))

Accuracy:  0.3
Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30

Confusion Matrix: 
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]


c:\Users\Hamad\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Hamad\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Hamad\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r